name: main

on: [push]

# env variable configuration
env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  DB_NAME: base-cluster
  USERS_COLLECTION_NAME: users
  VERIFICATION_COLLECTION_NAME: verification

# list of actions to run
jobs:
  test-database-connection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Modules
        run: npm install
      - name: Run tests
        run: npm run db-connection
  test-authentication-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Modules
        run: npm install
      - name: Run tests
        run: npm run authentication
  test-user-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Modules
        run: npm install
      - name: Run tests
        run: npm run user
